#!/usr/bin/env python3
"""Build native-resolution, 1-bit Inter glyphs for CMonoArt.

Regeneration requires Pillow and uharfbuzz. Neither runs on the ESP32.
"""

from pathlib import Path
import uharfbuzz as hb
from PIL import Image, ImageDraw, ImageFont


HERE = Path(__file__).resolve().parent
TTF = HERE / "Inter-Variable.ttf"
HEADER = HERE / "InterMono.h"
PREVIEW = HERE.parent / "previews" / "scene-1-inter-1645x288.png"
TV_PREVIEW = HERE.parent / "previews" / "scene-1-inter-tv-aspect.png"
FIRST = 32
LAST = 126
THRESHOLD = 118
FACES = (("Small", 27, 14, 500), ("Large", 43, 32, 450))


def shaped_width(font, text):
    buffer = hb.Buffer()
    buffer.add_str(text)
    buffer.guess_segment_properties()
    hb.shape(font, buffer, {"kern": True})
    return sum(item.x_advance for item in buffer.glyph_positions) / 64, len(buffer.glyph_positions)


def rasterize(size, optical_size, weight):
    source = TTF.read_bytes()
    hb_font = hb.Font(hb.Face(source))
    hb_font.scale = (size * 64, size * 64)
    hb_font.set_variations({"opsz": optical_size, "wght": weight})
    supersample = 4
    font = ImageFont.truetype(str(TTF), size * supersample)
    font.set_variation_by_axes([optical_size, weight])
    glyphs = []
    packed = bytearray()
    advances = {}
    for code in range(FIRST, LAST + 1):
        char = chr(code)
        advances[char] = shaped_width(hb_font, char)[0]
        canvas = Image.new("L", (size * 3 * supersample,
                                 size * 3 * supersample))
        origin_x = size
        baseline = size * 2
        ImageDraw.Draw(canvas).text(
            (origin_x * supersample, baseline * supersample),
            char, font=font, fill=255, anchor="ls"
        )
        # Integrate outline coverage before the final binary threshold. This
        # keeps diagonal and round edges more even than a single low-res pass.
        coverage = canvas.resize((size * 3, size * 3), Image.Resampling.BOX)
        binary = coverage.point(lambda v: 255 if v >= THRESHOLD else 0)
        bounds = binary.getbbox()
        offset = len(packed)
        advance = max(1, round(advances[char]))
        if bounds:
            left, top, right, bottom = bounds
            width, height = right - left, bottom - top
            stride = (width + 7) // 8
            for y in range(top, bottom):
                row = [0] * stride
                for x in range(left, right):
                    if binary.getpixel((x, y)):
                        column = x - left
                        row[column >> 3] |= 0x80 >> (column & 7)
                packed.extend(row)
            glyphs.append((offset, width, height, advance,
                           left - origin_x, top - baseline))
        else:
            glyphs.append((offset, 0, 0, advance, 0, 0))
    assert len(packed) < 65536
    kern = []
    for left in range(FIRST, LAST + 1):
        for right in range(FIRST, LAST + 1):
            a, b = chr(left), chr(right)
            width, count = shaped_width(hb_font, a + b)
            if count != 2:
                continue
            adjustment = round(width - advances[a] - advances[b])
            if adjustment:
                kern.append(((left - FIRST) * 95 + right - FIRST, adjustment))
    assert all(-128 <= amount <= 127 for _, amount in kern)
    return glyphs, packed, kern


def format_bytes(data):
    return "\n".join(
        "    " + ", ".join(f"0x{byte:02x}" for byte in data[i:i + 16]) + ","
        for i in range(0, len(data), 16)
    )


def write_header(faces):
    out = [
        "// Generated by generate_font.py from Inter-Variable.ttf.",
        "// Copyright 2020 The Inter Project Authors (https://github.com/rsms/inter).",
        "// Licensed under SIL Open Font License 1.1; see OFL.txt.",
        "// Source: https://github.com/google/fonts/tree/main/ofl/inter",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        "namespace CMonoFont {",
        "struct Glyph {",
        "    uint16_t offset;",
        "    uint8_t width, height, advance;",
        "    int8_t xOffset, yOffset;",
        "};",
        "struct KernPair { uint16_t key; int8_t adjustment; };",
        "struct Face {",
        "    const Glyph *glyphs;",
        "    const uint8_t *bits;",
        "    const KernPair *pairs;",
        "    uint16_t pairCount;",
        "};",
        "",
    ]
    for name, (glyphs, packed, kern) in faces.items():
        out.append(f"static const uint8_t k{name}Bits[] PROGMEM = {{")
        out.append(format_bytes(packed))
        out.append("};")
        out.append(f"static const Glyph k{name}Glyphs[] PROGMEM = {{")
        for code, (offset, width, height, advance, xoff, yoff) in enumerate(glyphs, FIRST):
            out.append(
                f"    {{{offset}, {width}, {height}, {advance}, {xoff}, {yoff}}},"
                f" // {code:3d} {repr(chr(code))}"
            )
        out.append("};")
        out.append(f"static const KernPair k{name}Pairs[] PROGMEM = {{")
        out.extend(f"    {{{key}, {amount}}}," for key, amount in kern)
        out.append("};")
        out.append(f"static const Face {name} = "
                   f"{{k{name}Glyphs, k{name}Bits, k{name}Pairs, {len(kern)}}};")
        out.append("")
    out += [
        "inline int kern(const Face &face, unsigned char left, unsigned char right) {",
        "    if (left < 32 || left > 126 || right < 32 || right > 126) return 0;",
        "    const uint16_t key = (left - 32) * 95 + right - 32;",
        "    int lo = 0, hi = face.pairCount;",
        "    while (lo < hi) {",
        "        const int mid = (lo + hi) >> 1;",
        "        if (face.pairs[mid].key < key) lo = mid + 1;",
        "        else hi = mid;",
        "    }",
        "    return lo < face.pairCount && face.pairs[lo].key == key ?",
        "        face.pairs[lo].adjustment : 0;",
        "}",
        "",
        "// x is the left edge; baseline is the common baseline for all glyphs.",
        "// scaleX corrects the narrow horizontal pixel aspect of PAL super mode.",
        "template<class Display>",
        "inline int draw(Display &display, int x, int baseline, const char *text,",
        "                const Face &face = Small, bool white = true,",
        "                int tracking = 1, int scaleX = 1) {",
        "    if (scaleX < 1) scaleX = 1;",
        "    unsigned char previous = 0;",
        "    for (; *text; ++text) {",
        "        const unsigned char code = static_cast<unsigned char>(*text);",
        "        if (code < 32 || code > 126) { previous = 0; continue; }",
        "        if (previous) x += kern(face, previous, code) * scaleX;",
        "        const Glyph &g = face.glyphs[code - 32];",
        "        const int stride = (g.width + 7) >> 3;",
        "        for (int row = 0; row < g.height; ++row) {",
        "            const int offset = g.offset + row * stride;",
        "            for (int col = 0; col < g.width; ++col) {",
        "                if (!(pgm_read_byte(face.bits + offset + (col >> 3)) &",
        "                      (0x80u >> (col & 7)))) continue;",
        "                const int px = x + (g.xOffset + col) * scaleX;",
        "                const int py = baseline + g.yOffset + row;",
        "                if (scaleX == 1) display.mono1Pixel(px, py, white);",
        "                else display.mono1FillRect(px, py, scaleX, 1, white);",
        "            }",
        "        }",
        "        x += (g.advance + tracking) * scaleX;",
        "        previous = code;",
        "    }",
        "    return x;",
        "}",
        "inline int measure(const char *text, const Face &face = Small,",
        "                   int tracking = 1, int scaleX = 1) {",
        "    if (scaleX < 1) scaleX = 1;",
        "    int width = 0;",
        "    unsigned char previous = 0;",
        "    for (; *text; ++text) {",
        "        const unsigned char code = static_cast<unsigned char>(*text);",
        "        if (code < 32 || code > 126) { previous = 0; continue; }",
        "        if (previous) width += kern(face, previous, code) * scaleX;",
        "        width += (face.glyphs[code - 32].advance + tracking) * scaleX;",
        "        previous = code;",
        "    }",
        "    return width;",
        "}",
        "} // namespace CMonoFont",
        "",
    ]
    HEADER.write_text("\n".join(out))


def preview(faces):
    image = Image.new("1", (1645, 288), 1)
    ink = ImageDraw.Draw(image)

    def glyph_text(x, baseline, message, face_name, color=0,
                   tracking=1, scale_x=1):
        glyphs, packed, pairs = faces[face_name]
        kern = dict(pairs)
        previous = None
        for char in message:
            if not (FIRST <= ord(char) <= LAST):
                previous = None
                continue
            code = ord(char)
            if previous is not None:
                x += kern.get((previous - FIRST) * 95 + code - FIRST, 0) * scale_x
            offset, width, height, advance, xoff, yoff = glyphs[code - FIRST]
            stride = (width + 7) // 8
            for row in range(height):
                for col in range(width):
                    if packed[offset + row * stride + (col >> 3)] & (0x80 >> (col & 7)):
                        px, py = x + (xoff + col) * scale_x, baseline + yoff + row
                        if 0 <= py < 288:
                            ink.rectangle((px, py, px + scale_x - 1, py), fill=color)
            x += (advance + tracking) * scale_x
            previous = code
        return x

    ink.rectangle((0, 0, 1644, 28), fill=0)
    glyph_text(20, 22, "CITADELA", "Small", color=1, scale_x=3)
    glyph_text(1190, 22, "TYPE / 02", "Small", color=1, scale_x=3)
    # Four source samples per glyph pixel approximate this TV mode's narrow
    # sample aspect. Splitting the alphabet keeps the font proportions intact.
    glyph_text(26, 68, "ABCDEFGHIJKLM", "Large", tracking=2, scale_x=4)
    glyph_text(26, 109, "NOPQRSTUVWXYZ", "Large", tracking=1, scale_x=4)
    glyph_text(26, 151, "abcdefghijklm", "Large", tracking=6, scale_x=4)
    glyph_text(26, 193, "nopqrstuvwxyz", "Large", tracking=5, scale_x=4)
    glyph_text(26, 244, "0123456789", "Large", tracking=6, scale_x=4)
    ink.line((1250, 215, 1250, 245), fill=0)
    glyph_text(1280, 237, "1645 PX", "Small", scale_x=3)
    ink.rectangle((0, 253, 1644, 287), fill=0)
    glyph_text(20, 279, "1 BIT / PIXEL", "Small", color=1, scale_x=3)
    glyph_text(1065, 279, "TAB NEXT", "Small", color=1, scale_x=3)
    PREVIEW.parent.mkdir(parents=True, exist_ok=True)
    image.save(PREVIEW)
    tv_coverage = image.convert("L").resize((384, 288), Image.Resampling.BOX)
    tv = tv_coverage.point(lambda value: 255 if value >= 128 else 0).convert("1")
    tv.resize((768, 576), Image.Resampling.NEAREST).save(TV_PREVIEW)


def main():
    faces = {name: rasterize(size, optical_size, weight)
             for name, size, optical_size, weight in FACES}
    write_header(faces)
    preview(faces)
    for name, (glyphs, packed, pairs) in faces.items():
        print(f"{name}: {len(glyphs)} glyphs, {len(packed)} bitmap bytes, "
              f"{len(pairs)} kern pairs")
    print(HEADER)
    print(PREVIEW)
    print(TV_PREVIEW)


if __name__ == "__main__":
    main()
